i18n/it/building.md
I began to refresh and update the Italian translations according to #8
=> updates it/building.md

i18n/en/building.md
Resolves #11. Sympathetic updates to kovri repo Makefile are forthcoming. Will reference this issue there.
=> English: update make options + build output + formatting

i18n/fr/faq.md, i18n/fr/index.md
Update translations to match the info from commit b08e7ad6c8077ae843c60ea1ff1d0986a984c89d
=> [French] Update translations to match english update

i18n/en/faq.md, i18n/en/index.md
=> English: complete the thought of the first sentence

i18n/en/faq.md
- Updated FAQ with more questions and reworded some existing answers
- Added anonimal's suggestions
=> Updated English FAQ.md

i18n/en/faq.md
Table isn't working, which I fixed, but it still didn't look good on smaller screens. Swapped it out for bullet point lists, which should also be better for translators.
=> Switched out the table for bullet points

i18n/en/acknowledgements.md, i18n/en/faq.md, i18n/fr/acknowledgements.md, i18n/fr/faq.md
faq.md and acknowledgements.md in french
=> French translation for faq.md, acknowledgements.md. And corrected 2 small mistakes in the english files.

i18n/da/acknowledgements.md, i18n/da/building.md, i18n/da/contributing.md, i18n/da/faq.md, i18n/da/index.md, i18n/da/quality.md, i18n/da/style.md, i18n/da/user_guide.md
Old pull request was a bit messy in the commits.
=> Danish translation - cleaned up

i18n/it/contributing.md
Hi, I've translated in Italian
=> Hi, I've translated in Italian Contributing.md

i18n/fr/README.md
This come along with monero-project/kovri#939
A single commit for a single file.
For review by @erciccione team.
=> Readme translated to French

i18n/it/README.md
This is the Italian version of the README according to the changes introducted with monero-project/kovri#906 
referencing #51
=> Add Italian version of the README

i18n/en/testnet_guide.md
Instructions for buidling, using, and destroying a Kovri testnet.
=> Testnet: basic user guide for current testnet

i18n/da/faq.md, i18n/de/faq.md, i18n/en/faq.md, i18n/fr/faq.md, i18n/ru/faq.md
=> i18n: update anonimal twitter handle

i18n/en/README_template.md
To make life easier for translators who whish to add a new language
=> Add Kovri README as template in /en

i18n/fr/README.md, i18n/it/README.md
Nothing else to say.
Up to you @erciccione and @anonimal 
Edit: French update for #63 to match monero-project/kovri#945
=> Update French & Italian Readme to match monero-project/kovri#945

i18n/sv/README.md
I'll PR the rest of the translated files when this one's merged
=> Created Swedish translation of README.md

i18n/en/user_guide.md
Building guide was removed. Resolves #69
=> English: add UPnP option, remove build guide link

i18n/da/developer_guide.md, i18n/de/developer_guide.md, i18n/es/developer_guide.md, i18n/it/developer_guide.md, i18n/ru/developer_guide.md
- Ready for translation
- Needed for Kovri Site to build correctly
=> Added developer guide (english version) to all other languages

i18n/da/README.md, i18n/de/README.md, i18n/en/README_template.md, i18n/es/README.md, i18n/fr/README.md, i18n/it/README.md, i18n/ru/README.md, i18n/sv/README.md
updated link to Kovri's Moneropedia entry
=> update READMEs to match monero-project/kovri#967

i18n/fr/testnet_guide.md
This is the French translation of testnet guide added in #56
=> French translation of latest testnet guide

i18n/da/user_guide.md, i18n/de/user_guide.md, i18n/en/user_guide.md, i18n/es/user_guide.md, i18n/fr/user_guide.md, i18n/it/user_guide.md, i18n/ru/user_guide.md
=> user_guide: update platform binary paths

i18n/en/monero_guide.md
Overlooked/copypasta'd during the rush to get the release out.
=> English: fix SIGHUP command in monero guide

i18n/fr/monero_guide.md
Latest Monero guide translation to French.
This is the #92 French solution, and need #98 to be lightened from French file (otherwise, i'll have to rebase and solve conflict next to #98 merge).
=> Monero guide French translation

i18n/da/monero_guide.md, i18n/es/monero_guide.md, i18n/it/monero_guide.md, i18n/ru/monero_guide.md, i18n/sv/monero_guide.md
Except for German, since it's  being added by #96
Will open task on Taiga asking for translators once this get merged (see #92 )
=> Add monero_guide.md for all languages

i18n/de/README.md, i18n/es/README.md, i18n/fr/README.md, i18n/it/README.md, i18n/sv/README.md
=> README: remove rest of "Alpha release coming soon"

i18n/da/faq.md, i18n/de/faq.md, i18n/es/faq.md, i18n/fr/faq.md, i18n/it/faq.md
wording taken from respective README translations for 'developer guide'
=> faq: Localize link to dev guide
